{
 "title": "ACTUATORS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "WHOLE_ACTUATORS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iotproject",
     "rawSql": "SELECT CAST(state AS UNSIGNED) AS state_int, timestamp\nFROM iotproject.actuators"
    }
   ]
  },
  {
   "title": "TEMPERATURE_ACTUATORS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "iotproject",
     "rawSql": "SELECT CAST(state AS UNSIGNED) AS state_int, timestamp\nFROM iotproject.actuators\nWHERE topic='temperature_actuator'"
    }
   ]
  },
  {
   "title": "HUMIDITY_ACTUATORS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "iotproject",
     "rawSql": "SELECT CAST(state AS UNSIGNED) AS state_int, timestamp\nFROM iotproject.actuators\nWHERE topic='humidity_actuator'"
    }
   ]
  },
  {
   "title": "CO2_ACTUATORS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "iotproject",
     "rawSql": "SELECT CAST(state AS UNSIGNED) AS state_int, timestamp\nFROM iotproject.actuators\nWHERE topic='co2_actuator'"
    }
   ]
  }
 ]
}