{
 "title": "SENSORS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HUMIDITY_SENSORS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iotproject",
     "rawSql": "SELECT * FROM iotproject.sensors WHERE topic = 'humidity'"
    }
   ]
  },
  {
   "title": "CO2_SENSORS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "iotproject",
     "rawSql": "SELECT * FROM iotproject.sensors WHERE topic = 'co2'"
    }
   ]
  },
  {
   "title": "TEMPERATURE_SENSORS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "iotproject",
     "rawSql": "SELECT * FROM iotproject.sensors WHERE topic = 'temperature'; "
    }
   ]
  },
  {
   "title": "WHOLE_SENSORS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "iotproject",
     "rawSql": "SELECT * FROM iotproject.sensors "
    }
   ]
  }
 ]
}